#!/bin/bash

cat << EOF

This spell will engulf your enemy in flames!

Add it to your spellbook by creating a variable and adding the spell to it, 
like this: 

export Spells=fire,\$Spells

You can always see which spells you have by using this command:

echo \$Spells
EOF
