#!/bin/bash


cat << EOF

This spell will momentarily stun your enemy!

Add it to your spellbook by creating a variable and adding the spell to it, 
like this:

export Spells=stun,\$Spells

You can always see which spells you have by using this command:

echo \$Spells
EOF
