#!/bin/bash

cat << EOF

WAIT!! Before you continue to your fight with the training dummy, be sure 
you have taken a look and added the other spells that are here to your 
spellbook! If you have then please continue to your doom.


A training dummy stands before you. It emits an unnatural aura, as if 
this will be the most powerful enemy you shall face. What do you do?
EOF

echo ""
echo "Pick from the choices below: "
echo ""
echo "Spells you have learned: $Spells"
echo ""
echo "Or beg"
echo ""
echo -n "Make your choice: "

read choice

if [ "$choice" = "stun" ]; then
	cat << EOF

A bright flash erupts from the tip of your wand and stuns your 
enemy. Well done!
EOF

elif [ "$choice" = "fire" ]; then
	cat << EOF

The air begins to crackle and your enemy is engulfed in flames. All that 
is left is a pile of ashes. Well done!
EOF

elif [ "$choice" = "beg" ]; then
	cat << EOF

You get on your knees before the training dummy and grovel, begging to walk 
away with your life. The training dummy allows this, and you walk away unharmed.
EOF

fi
